/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Alex
 */
public class administradorJava extends javax.swing.JFrame {

    /**
     * Creates new form administradorJava
     */
    public administradorJava() {
        this.setUndecorated(true);
        initComponents();
        this.setTitle("Administrador de archivos JAVA");
        this.setLocation(420, 220);
//        this.setResizable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_mini = new javax.swing.JButton();
        btn_cerrar = new javax.swing.JButton();
        btn_ajustar = new javax.swing.JButton();
        select = new javax.swing.JComboBox<>();
        btn_subir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_ruta = new javax.swing.JTextField();
        btn_salir = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btn_abrir2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_mini.setBackground(new java.awt.Color(0, 0, 0));
        btn_mini.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/minimizar_1.png"))); // NOI18N
        btn_mini.setPreferredSize(new java.awt.Dimension(70, 50));
        btn_mini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_miniActionPerformed(evt);
            }
        });
        getContentPane().add(btn_mini, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 20, 35, 35));

        btn_cerrar.setBackground(new java.awt.Color(0, 0, 0));
        btn_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png"))); // NOI18N
        btn_cerrar.setMaximumSize(new java.awt.Dimension(67, 52));
        btn_cerrar.setMinimumSize(new java.awt.Dimension(67, 52));
        btn_cerrar.setPreferredSize(new java.awt.Dimension(70, 50));
        btn_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cerrarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 20, 35, 35));

        btn_ajustar.setBackground(new java.awt.Color(0, 0, 0));
        btn_ajustar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fullscreen.png"))); // NOI18N
        btn_ajustar.setPreferredSize(new java.awt.Dimension(70, 50));
        btn_ajustar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ajustarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_ajustar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 20, 35, 35));

        select.setBackground(new java.awt.Color(51, 51, 51));
        select.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        select.setForeground(new java.awt.Color(255, 255, 255));
        select.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona la Categoría", "Archivos Personales", "Archivos escuela", "Archivos Servicio Social ", "Archivos Publicos" }));
        select.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectActionPerformed(evt);
            }
        });
        getContentPane().add(select, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 500, 40));

        btn_subir.setBackground(new java.awt.Color(0, 153, 255));
        btn_subir.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        btn_subir.setForeground(new java.awt.Color(0, 0, 0));
        btn_subir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/subir.png"))); // NOI18N
        btn_subir.setText("Subir");
        btn_subir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_subirActionPerformed(evt);
            }
        });
        getContentPane().add(btn_subir, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 230, 120, 40));
        btn_subir.getAccessibleContext().setAccessibleDescription("");

        jLabel2.setFont(new java.awt.Font("Bradley Hand ITC", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 255));
        jLabel2.setText("Administrador de archivos JAVA");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 560, 50));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Aqui se mostraran los resultados de las categorias");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, 570, 40));

        txt_ruta.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        txt_ruta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_rutaActionPerformed(evt);
            }
        });
        getContentPane().add(txt_ruta, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 500, 40));

        btn_salir.setBackground(new java.awt.Color(204, 0, 0));
        btn_salir.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        btn_salir.setForeground(new java.awt.Color(255, 255, 255));
        btn_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png"))); // NOI18N
        btn_salir.setText("Salir");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });
        getContentPane().add(btn_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 680, 120, 40));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ingresa la ruta del archivo ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 400, 40));

        jTable1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", ".doc", "Ejemplo.doc", "C:/Users/Admin/Documents", "10-05-2021", "Abrir"},
                {"2", ".doc", "Ejemplo1.doc", "C:/Users/Admin/Documents", "10-05-2021", "Abrir"},
                {"3", ".pdf", "Ejemplo.pdf", "C:/Users/Admin/Documents", "19-05-2021", "Abrir"},
                {"4", ".xlsx", "Ejemplo.xlsx", "C:/Users/Admin/Documents", "22-05-2021", "Abrir"},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Tipo ", "Nombre del archivo", "Ubicación", "Fecha ", "Abrir"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setToolTipText("");
        jTable1.setGridColor(new java.awt.Color(0, 0, 0));
        jTable1.setShowHorizontalLines(false);
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 1050, 310));

        btn_abrir2.setBackground(new java.awt.Color(0, 102, 0));
        btn_abrir2.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        btn_abrir2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/folder.png"))); // NOI18N
        btn_abrir2.setText("Abrir");
        btn_abrir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_abrir2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_abrir2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 120, 120, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectActionPerformed
        
    }//GEN-LAST:event_selectActionPerformed

    private void btn_subirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_subirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_subirActionPerformed

    private void btn_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cerrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_cerrarActionPerformed

    private void btn_ajustarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ajustarActionPerformed
        this.setExtendedState(MAXIMIZED_BOTH);
    }//GEN-LAST:event_btn_ajustarActionPerformed

    private void btn_miniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_miniActionPerformed
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_btn_miniActionPerformed

    private void txt_rutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_rutaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_rutaActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        int resp = javax.swing.JOptionPane.showConfirmDialog(null, "¿Está seguro?","Alerta!!",javax.swing.JOptionPane.YES_NO_OPTION);
        if (resp == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_btn_salirActionPerformed

    private void btn_abrir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_abrir2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_abrir2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(administradorJava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(administradorJava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(administradorJava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(administradorJava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new administradorJava().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_abrir2;
    private javax.swing.JButton btn_ajustar;
    private javax.swing.JButton btn_cerrar;
    private javax.swing.JButton btn_mini;
    private javax.swing.JButton btn_salir;
    private javax.swing.JButton btn_subir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> select;
    private javax.swing.JTextField txt_ruta;
    // End of variables declaration//GEN-END:variables
}
